// frontend/src/features/auth/LoginPage.tsx
import { useEffect, useRef, useState, type FormEvent } from 'react'
import { Eye, EyeOff } from 'lucide-react'
import { Navigate, useLocation } from 'react-router'
import { BrandMetaballs } from '@/shared/brand/BrandMetaballs'
import { cn } from '@/shared/lib/cn'
import { Button } from '@/shared/ui/button'
import { Field, FieldAction, FieldActions, Input } from '@/shared/ui/field'
import { SegmentedControl } from '@/shared/ui/segmented-control'
import { useFeedback } from '@/shared/ui/feedback-context'
import { login, register } from './api'
import { useAuth } from '@/features/auth'

type AuthMode = 'login' | 'register'

export function LoginPage() {
  const [mode, setMode] = useState<AuthMode>('login')
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [email, setEmail] = useState('')
  const [showPassword, setShowPassword] = useState(false)
  const [busy, setBusy] = useState(false)
  const auth = useAuth()
  const feedback = useFeedback()
  const location = useLocation()
  const reportedExpiration = useRef(false)

  useEffect(() => {
    const expired = new URLSearchParams(location.search).get('reason') === 'expired'
    if (!expired) reportedExpiration.current = false
    else if (!reportedExpiration.current) {
      reportedExpiration.current = true
      feedback.notify('登录已失效，请重新登录。', 'error')
    }
  }, [feedback, location.search])

  const switchMode = (next: AuthMode) => {
    setMode(next)
    setPassword('')
    setEmail('')
  }

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    if (username.trim().length < 2) {
      feedback.notify('用户名至少需要 2 个字符', 'error')
      document.getElementById('auth-username')?.focus()
      return
    }
    if (password.length < 6) {
      feedback.notify('密码至少需要 6 个字符', 'error')
      document.getElementById('auth-password')?.focus()
      return
    }

    setBusy(true)
    try {
      if (mode === 'register') {
        await register(username.trim(), password, email.trim() || undefined)
        feedback.notify('注册成功，请继续登录。', 'success')
        switchMode('login')
        return
      }
      const result = await login(username.trim(), password)
      await auth.signIn(result.accountId)
    } catch (reason) {
      feedback.notify(reason instanceof Error ? reason.message : '请求失败', 'error')
    } finally {
      setBusy(false)
    }
  }

  if (auth.status === 'authenticated') {
    const redirect = new URLSearchParams(location.search).get('redirect') || '/interview'
    return <Navigate to={redirect} replace />
  }

  return (
    <main className="page page--center page--auth">
      <section className="login-card" aria-labelledby="auth-title">
        <div className="login-card__content">
          <aside className="login-card__brand-panel">
            <BrandMetaballs className="login-card__logo" />
            <p className="login-card__brand-caption">AI Mock Interview</p>
          </aside>

          <div className="login-card__form-panel">
            <header className="login-card__header">
              <h1 id="auth-title" className="type-hero">
                {mode === 'login' ? '进入面试工作台' : '创建工作台账号'}
              </h1>
            </header>

            <SegmentedControl
              ariaLabel="账号操作"
              items={[
                { value: 'login', label: '登录' },
                { value: 'register', label: '注册' },
              ]}
              value={mode}
              onValueChange={switchMode}
            />

            <form
              data-slot="auth-form"
              className="flex min-h-0 flex-col gap-md"
              onSubmit={(event) => void submit(event)}
              noValidate
            >
              <Field label="用户名" htmlFor="auth-username">
                <Input
                  id="auth-username"
                  value={username}
                  onChange={(event) => setUsername(event.target.value)}
                  autoComplete="username"
                  placeholder="请输入用户名"
                  required
                />
              </Field>

              <Field label="密码" htmlFor="auth-password">
                <FieldActions
                  actions={[
                    <FieldAction
                      label={showPassword ? '隐藏密码' : '显示密码'}
                      icon={showPassword ? <Eye /> : <EyeOff />}
                      onClick={() => setShowPassword((value) => !value)}
                    />,
                  ]}
                >
                  <Input
                    id="auth-password"
                    value={password}
                    onChange={(event) => setPassword(event.target.value)}
                    type={showPassword ? 'text' : 'password'}
                    autoComplete={mode === 'login' ? 'current-password' : 'new-password'}
                    placeholder="请输入密码"
                    required
                  />
                </FieldActions>
              </Field>

              <div
                className={cn('auth-email-field', mode === 'register' && 'is-visible')}
                aria-hidden={mode !== 'register'}
              >
                <Field label="邮箱" htmlFor="auth-email">
                  <Input
                    id="auth-email"
                    value={email}
                    onChange={(event) => setEmail(event.target.value)}
                    type="email"
                    autoComplete="email"
                    placeholder="请输入邮箱"
                    disabled={mode !== 'register'}
                  />
                </Field>
              </div>

              <div className="login-card__actions">
                <Button type="submit" className="w-full" loading={busy}>
                  {mode === 'login' ? '登录' : '完成注册'}
                </Button>
              </div>
            </form>
          </div>
        </div>
      </section>
    </main>
  )
}

// frontend/src/features/auth/pages/LoginPage.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { login as loginRequest, register as registerRequest } from '../api/auth'
import BrandMetaballs from '@/shared/brand/BrandMetaballs.vue'
import { usePageNotice } from '@/shared/ui/sonner/usePageNotice'
import { useAuthStore } from '../model/authStore'
import { getErrorMessage } from '@/shared/lib/errors'
import { withMinDelay } from '@/shared/lib/utils'
import SegmentedControl from '@/shared/ui/segmented-control/SegmentedControl.vue'
import { Button } from '@/shared/ui/button'
import { Input } from '@/shared/ui/input'
import { Eye, EyeOff } from '@lucide/vue'
import { FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/shared/ui/form'
import { useForm } from 'vee-validate'
import { toTypedSchema } from '@vee-validate/zod'
import { loginSchema, registerSchema } from '../model/schema'

type AuthMode = 'login' | 'register'

const router = useRouter()
const route = useRoute()
const authStore = useAuthStore()
const { showNotice } = usePageNotice()

const authMode = ref<AuthMode>('login')
const loading = ref(false)
const showPassword = ref(false)

const redirectTarget = computed(() => {
  return typeof route.query.redirect === 'string' && route.query.redirect
    ? route.query.redirect
    : '/interview'
})

const expiredNotice = computed(() => route.query.reason === 'expired')
const isRegisterMode = computed(() => authMode.value === 'register')
const authEyebrow = computed(() => (isRegisterMode.value ? '注册' : '登录'))
const authTitle = computed(() => (isRegisterMode.value ? '创建工作台账号' : '进入面试工作台'))
const submitLabel = computed(() => (isRegisterMode.value ? '完成注册' : '登录'))

const currentSchema = computed(() =>
  isRegisterMode.value ? toTypedSchema(registerSchema) : toTypedSchema(loginSchema),
)

const { handleSubmit, setValues, resetForm } = useForm({
  validationSchema: currentSchema,
})

function switchMode(mode: AuthMode) {
  authMode.value = mode
  resetForm()
}

const submitAuth = handleSubmit(async (values) => {
  loading.value = true

  try {
    if (isRegisterMode.value) {
      const v = values as any
      await withMinDelay(
        registerRequest(v.username.trim(), v.password, v.email?.trim() || undefined),
      )
      showNotice('注册成功，请继续登录。', 'success')
      authMode.value = 'login'
      setValues({ username: v.username })
    } else {
      const response = await withMinDelay(loginRequest(values.username.trim(), values.password))
      authStore.setToken(response.token)
      await router.replace(redirectTarget.value)
    }
  } catch (error) {
    showNotice(getErrorMessage(error), 'error')
  } finally {
    loading.value = false
  }
})

onMounted(() => {
  if (expiredNotice.value) {
    showNotice('登录已失效，请重新登录。', 'warning')
  }
})
</script>

<template>
  <section class="page page--center page--auth">
    <div class="login-card">
      <div class="login-card__content">
        <aside class="login-card__brand-panel">
          <BrandMetaballs class="login-card__logo" />
          <p class="login-card__brand-caption">AI Mock Interview</p>
        </aside>

        <div class="login-card__form-panel">
          <div class="page__header login-card__header">
            <p class="eyebrow">{{ authEyebrow }}</p>
            <h2 class="page__title">{{ authTitle }}</h2>
          </div>

          <div class="mb-6">
            <SegmentedControl
              :items="['登录', '注册']"
              :model-value="isRegisterMode ? '注册' : '登录'"
              @update:model-value="(val) => switchMode(val === '注册' ? 'register' : 'login')"
            />
          </div>

          <form class="flex flex-col gap-lg w-full" @submit.prevent="submitAuth">
            <FormField name="username" v-slot="{ componentField }">
              <FormItem>
                <FormLabel>用户名</FormLabel>
                <FormControl>
                  <Input
                    v-bind="componentField"
                    autocomplete="username"
                    placeholder="请输入用户名"
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            </FormField>

            <FormField name="password" v-slot="{ componentField }">
              <FormItem class="relative">
                <FormLabel>密码</FormLabel>
                <FormControl>
                  <div class="relative w-full">
                    <Input
                      v-bind="componentField"
                      autocomplete="current-password"
                      placeholder="请输入密码"
                      :type="showPassword ? 'text' : 'password'"
                      class="pr-10"
                    />
                    <button
                      type="button"
                      :aria-label="showPassword ? '隐藏密码' : '显示密码'"
                      class="absolute right-0 top-0 h-full px-3 py-2 hover:bg-transparent text-muted-foreground flex items-center justify-center focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-focus"
                      @click="showPassword = !showPassword"
                    >
                      <Eye v-if="showPassword" class="h-4 w-4" />
                      <EyeOff v-else class="h-4 w-4" />
                    </button>
                  </div>
                </FormControl>
                <FormMessage />
              </FormItem>
            </FormField>

            <div
              :class="[
                'transition-opacity [transition-duration:var(--motion-duration-base)] [transition-timing-function:var(--motion-ease-standard)]',
                isRegisterMode
                  ? 'opacity-100 pointer-events-auto'
                  : 'opacity-0 pointer-events-none',
              ]"
              :aria-hidden="!isRegisterMode"
            >
              <FormField name="email" v-slot="{ componentField }">
                <FormItem>
                  <FormLabel>邮箱</FormLabel>
                  <FormControl>
                    <Input
                      v-bind="componentField"
                      autocomplete="email"
                      :disabled="!isRegisterMode"
                      placeholder="请输入邮箱"
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              </FormField>
            </div>

            <div class="pt-2">
              <Button
                type="submit"
                class="w-full font-serif"
                :disabled="loading"
                :loading="loading"
              >
                {{ submitLabel }}
              </Button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
</template>
