// frontend/src/features/settings/LlmSettingsPanel.tsx
import { Eye, EyeOff, RefreshCw, Trash2 } from 'lucide-react'
import { useQuery } from '@tanstack/react-query'
import { Button, Field, IconTooltip, Input, Select } from '@/shared/ui'
import { useLlmSettings } from './useLlmSettings'
import { fetchLlmConfig, fetchProviders } from './api'

export function LlmSettingsPanel({ providerKey }: { providerKey?: string }) {
  const config = useQuery({ queryKey: ['llm-config'], queryFn: fetchLlmConfig })
  const providers = useQuery({ queryKey: ['llm-providers'], queryFn: fetchProviders })
  if (config.isPending || providers.isPending)
    return <div className="empty-state">正在读取模型配置…</div>
  const error = config.error || providers.error
  if (error || !config.data || !providers.data)
    return <div className="empty-state">{error?.message ?? '模型配置不可用'}</div>
  return (
    <LlmSettingsForm
      key={`${providerKey ?? config.data.providerKey}:${config.data.baseUrl}:${config.data.model}`}
      config={config.data}
      providers={providers.data}
      providerKey={providerKey}
    />
  )
}

function LlmSettingsForm({
  config,
  providers,
  providerKey,
}: {
  config: Awaited<ReturnType<typeof fetchLlmConfig>>
  providers: Awaited<ReturnType<typeof fetchProviders>>
  providerKey?: string
}) {
  const state = useLlmSettings(config, providers, providerKey)
  const endpointHint = state.protocol
    ? `填写接口根地址，系统会请求 ${state.protocol.endpointSuffix}。`
    : 'DeepSeek 使用系统配置的服务地址。'
  return (
    <div className="panel-content-wrapper">
      <Field label="服务协议" htmlFor="llm-provider">
        <Select
          id="llm-provider"
          value={state.draft.providerKey}
          options={state.providers.map((provider) => ({
            value: provider.providerKey,
            label: provider.displayName,
          }))}
          onValueChange={state.selectProvider}
        />
      </Field>
      {state.custom && (
        <Field label="Base URL" htmlFor="llm-base-url" hint={endpointHint}>
          <div className="endpoint-row">
            <Input
              id="llm-base-url"
              value={state.draft.baseUrl ?? ''}
              placeholder={state.protocol?.placeholder}
              onChange={(event) => state.update('baseUrl', event.target.value)}
            />
            {state.protocol?.modelDiscovery && (
              <Button
                type="button"
                variant="secondary"
                loading={state.discovering}
                onClick={state.discover}
              >
                <RefreshCw size={15} />
                检测模型
              </Button>
            )}
          </div>
        </Field>
      )}
      <Field label="模型" htmlFor="llm-model">
        {state.models.length ? (
          <Select
            id="llm-model"
            value={state.draft.model}
            options={[...new Set([state.draft.model, ...state.models])]
              .filter(Boolean)
              .map((model) => ({ value: model, label: model }))}
            onValueChange={(value) => state.update('model', value)}
          />
        ) : (
          <Input
            id="llm-model"
            value={state.draft.model}
            placeholder="输入模型 ID"
            onChange={(event) => state.update('model', event.target.value)}
          />
        )}
      </Field>
      <Field
        label="API Key"
        htmlFor="llm-api-key"
        hint={
          state.config?.hasApiKey && state.config.apiKeyMasked
            ? `已保存 ${state.config.apiKeyMasked}`
            : undefined
        }
      >
        <div className="password-field">
          <Input
            id="llm-api-key"
            type={state.showKey ? 'text' : 'password'}
            autoComplete="off"
            value={state.draft.apiKey ?? ''}
            placeholder="留空表示保留当前 Key"
            onChange={(event) => state.update('apiKey', event.target.value)}
          />
          <div className="password-field__actions">
            {state.config?.hasApiKey && (
              <IconTooltip label="清除已保存的 API Key">
                <button
                  className="password-toggle ui-action ui-action-icon"
                  type="button"
                  aria-label="清除已保存的 API Key"
                  onClick={() => state.update('apiKey', '__CLEAR__')}
                >
                  <Trash2 size={16} />
                </button>
              </IconTooltip>
            )}
            <IconTooltip label={state.showKey ? '隐藏 API Key' : '显示 API Key'}>
              <button
                className="password-toggle ui-action ui-action-icon"
                type="button"
                aria-label={state.showKey ? '隐藏 API Key' : '显示 API Key'}
                onClick={() => state.setShowKey(!state.showKey)}
              >
                {state.showKey ? <Eye size={16} /> : <EyeOff size={16} />}
              </button>
            </IconTooltip>
          </div>
        </div>
      </Field>
      <section className="settings-form-section">
        <h3 className="settings-form-section__title">高级设置</h3>
        <div className="advanced-grid">
          <Field label="最大回复长度" htmlFor="llm-max-tokens">
            <Select
              id="llm-max-tokens"
              value={state.draft.maxTokens ? String(state.draft.maxTokens) : ''}
              options={[
                { value: '', label: '模型默认' },
                { value: '4096', label: '常规 (4096)' },
                { value: '8192', label: '长回复 (8192)' },
                { value: '32768', label: '深度分析 (32768)' },
              ]}
              onValueChange={(value) =>
                state.update('maxTokens', value ? Number(value) : undefined)
              }
            />
          </Field>
          <Field label="思考深度" htmlFor="llm-thinking-depth">
            <Select
              id="llm-thinking-depth"
              value={state.draft.thinkingDepth ?? ''}
              options={[
                { value: '', label: '默认' },
                { value: 'low', label: '低' },
                { value: 'medium', label: '中' },
                { value: 'high', label: '高' },
                { value: 'xhigh', label: '极高' },
              ]}
              onValueChange={(value) => state.update('thinkingDepth', value || null)}
            />
          </Field>
        </div>
      </section>
      {state.testMessage && (
        <p className="helper-text" role="status">
          {state.testMessage}
        </p>
      )}
      <div className="settings-inline-actions settings-inline-actions--header">
        <Button
          variant="secondary"
          loading={state.testing}
          disabled={state.saving}
          onClick={state.test}
        >
          测试连接
        </Button>
        <Button loading={state.saving} disabled={state.testing} onClick={state.save}>
          保存设置
        </Button>
      </div>
    </div>
  )
}

// frontend/src/components/workspace/LlmSettingsPanel.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useLlmSettings } from '../../composables/useLlmSettings'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Eye, EyeOff, Trash2 } from '@lucide/vue'
import {
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form'
import { useForm } from 'vee-validate'
import { toTypedSchema } from '@vee-validate/zod'
import { llmSettingsSchema } from '../../schemas/llm'

const OPENAI_COMPATIBLE_PROVIDER = 'openai-compatible'

// 前端展示映射：后端 providerKey 仍为 openai-compatible，仅展示层映射为对普通用户友好的名称。
const DISPLAY_NAME_MAP: Record<string, string> = {
  [OPENAI_COMPATIBLE_PROVIDER]: '自定义 OpenAI 兼容接口',
}

const {
  loading, saving, testing, discovering, testStatus,
  providerOptions, selectedProviderKey, selectedModel,
  baseUrlInput, apiKeyInput, apiKeyMasked, maxTokens, thinkingDepth,
  modelOptions, isOpenAiCompatible,
  loadSettings, saveSettings, clearApiKey, testSettings, discoverModels,
} = useLlmSettings()

const showApiKey = ref(false)

const { handleSubmit, setValues } = useForm({
  validationSchema: toTypedSchema(llmSettingsSchema),
})

function providerDisplayName(key: string, fallback: string): string {
  return DISPLAY_NAME_MAP[key] ?? fallback
}

// 测试状态 Badge 映射。
const testBadgeVariant = computed(() => {
  switch (testStatus.value.state) {
    case 'testing': return 'secondary'
    case 'success': return 'default'
    case 'error': return 'destructive'
    default: return 'outline'
  }
})
const testBadgeText = computed(() => {
  switch (testStatus.value.state) {
    case 'testing': return '测试中'
    case 'success': return '已通过'
    case 'error': return '失败'
    default: return '未测试'
  }
})
const apiKeyStatusLabel = computed(() => apiKeyMasked.value ? `已保存：${apiKeyMasked.value}` : '未保存')

watch([selectedProviderKey, baseUrlInput, selectedModel, apiKeyInput, maxTokens, thinkingDepth], () => {
  setValues({
    providerKey: selectedProviderKey.value,
    baseUrl: baseUrlInput.value,
    model: selectedModel.value,
    apiKey: apiKeyInput.value,
    maxTokens: maxTokens.value,
    thinkingDepth: thinkingDepth.value,
  })
}, { immediate: true })

const onSubmit = handleSubmit(async () => {
  await saveSettings()
})

onMounted(() => {
  void loadSettings()
})

defineExpose({ submit: onSubmit, test: testSettings, saving, testing, loading })
</script>

<template>
  <div class="panel-content-wrapper">
    <form class="flex flex-col gap-6" @submit.prevent="onSubmit">

      <div class="field-grid">
        <FormField name="providerKey" v-slot="{ componentField }">
          <FormItem>
            <FormLabel>接入方式</FormLabel>
            <Select v-bind="componentField" v-model="selectedProviderKey">
              <SelectTrigger>
                <SelectValue placeholder="请选择接入方式" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem
                  v-for="provider in providerOptions"
                  :key="provider.providerKey"
                  :value="provider.providerKey"
                >
                  {{ providerDisplayName(provider.providerKey, provider.displayName) }}
                </SelectItem>
              </SelectContent>
            </Select>
            <FormMessage />
          </FormItem>
        </FormField>

        <FormField name="model" v-slot="{ componentField }">
          <FormItem>
            <FormLabel>模型</FormLabel>
            <!-- 自定义接口：可手填模型 ID（datalist 提供候选但不阻止手动输入）；内置 provider 保持 Select -->
            <Select
              v-if="!isOpenAiCompatible"
              :disabled="modelOptions.length === 0"
              v-bind="componentField"
              v-model="selectedModel"
            >
              <SelectTrigger>
                <SelectValue placeholder="请选择模型" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem
                  v-for="model in modelOptions"
                  :key="model"
                  :value="model"
                >
                  {{ model }}
                </SelectItem>
              </SelectContent>
            </Select>
            <template v-else>
              <FormControl>
                <Input
                  v-model="selectedModel"
                  v-bind="componentField"
                  list="llm-model-suggestions"
                  autocomplete="off"
                  placeholder="填写或选择模型 ID"
                />
              </FormControl>
              <datalist id="llm-model-suggestions">
                <option v-for="model in modelOptions" :key="model" :value="model" />
              </datalist>
            </template>
            <FormMessage />
          </FormItem>
        </FormField>
      </div>

      <FormField v-if="isOpenAiCompatible" name="baseUrl" v-slot="{ componentField }">
        <FormItem>
          <FormLabel>Base URL</FormLabel>
          <div class="endpoint-row">
            <FormControl>
              <Input
                v-model="baseUrlInput"
                v-bind="componentField"
                autocomplete="off"
                placeholder="例如：https://api.deepseek.com/v1"
              />
            </FormControl>
            <Button
              type="button"
              variant="secondary"
              class="endpoint-row__button"
              :disabled="discovering"
              :loading="discovering"
              @click="discoverModels"
            >
              自动检测模型
            </Button>
          </div>
          <p class="helper-text">填写接口根地址，通常以 /v1 结尾；不要填写 /chat/completions。</p>
          <FormMessage />
        </FormItem>
      </FormField>

      <FormField name="apiKey" v-slot="{ componentField }">
        <FormItem class="relative">
          <FormLabel>API Key</FormLabel>
          <div class="relative w-full flex items-center">
            <FormControl>
              <Input
                v-model="apiKeyInput"
                v-bind="componentField"
                autocomplete="off"
                placeholder="留空表示不修改当前 Key"
                :type="showApiKey ? 'text' : 'password'"
                class="pr-20"
              />
            </FormControl>
            <div class="absolute right-0 top-0 h-full flex items-center pr-1">
              <button
                v-if="apiKeyMasked"
                type="button"
                aria-label="清除 API Key"
                class="px-2 py-2 hover:bg-transparent text-muted-foreground hover:text-destructive flex items-center justify-center transition-colors duration-300 ease-in-out"
                @click="clearApiKey"
              >
                <Trash2 class="h-4 w-4" />
              </button>
              <button
                type="button"
                :aria-label="showApiKey ? '隐藏 API Key' : '显示 API Key'"
                class="px-2 py-2 hover:bg-transparent text-muted-foreground flex items-center justify-center transition-colors duration-300 ease-in-out"
                @click="showApiKey = !showApiKey"
              >
                <Eye v-if="showApiKey" class="h-4 w-4" />
                <EyeOff v-else class="h-4 w-4" />
              </button>
            </div>
          </div>
          <p class="helper-text api-key-status">{{ apiKeyStatusLabel }}</p>
          <FormMessage />
        </FormItem>
      </FormField>

      <!-- 持久测试状态：不依赖 2 秒 toast，表单内始终可见 -->
      <div class="test-status-row">
        <span class="test-status-row__label">连接测试</span>
        <Badge :variant="testBadgeVariant">{{ testBadgeText }}</Badge>
        <span class="test-status-row__message" :class="{ 'test-status-row__message--error': testStatus.state === 'error' }">
          {{ testStatus.message }}
        </span>
      </div>

      <div class="form-section">
        <div class="form-section__title">高级设置</div>
        <div class="advanced-grid">
          <FormField name="maxTokens" v-slot="{ componentField }">
            <FormItem>
              <FormLabel>最大回复长度 (Max Tokens)</FormLabel>
              <FormControl>
                <Select v-bind="componentField" :model-value="maxTokens ? String(maxTokens) : 'auto'" @update:model-value="v => maxTokens = v === 'auto' ? undefined : Number(v)">
                  <SelectTrigger class="w-full">
                    <SelectValue placeholder="模型默认 (Auto)" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="auto">模型默认 (Auto)</SelectItem>
                    <SelectItem value="4096">常规 (4096)</SelectItem>
                    <SelectItem value="8192">长回复 (8192)</SelectItem>
                    <SelectItem value="32768">深度分析 (32768)</SelectItem>
                  </SelectContent>
                </Select>
              </FormControl>
              <FormMessage />
            </FormItem>
          </FormField>

          <FormField name="thinkingDepth" v-slot="{ componentField }">
            <FormItem>
              <FormLabel>思考深度 (Thinking Depth)</FormLabel>
              <Select v-bind="componentField">
                <SelectTrigger>
                  <SelectValue placeholder="默认 (Default)" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="low">低 (Low)</SelectItem>
                  <SelectItem value="medium">中 (Medium)</SelectItem>
                  <SelectItem value="high">高 (High)</SelectItem>
                  <SelectItem value="xhigh">极高 (Extreme)</SelectItem>
                </SelectContent>
              </Select>
              <p class="helper-text">部分模型可能不支持，测试失败时请改回默认。</p>
              <FormMessage />
            </FormItem>
          </FormField>
        </div>
      </div>

    </form>
  </div>
</template>

<style scoped>
.panel-content-wrapper {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-md);
}
.form-section {
  margin-top: var(--spacing-md);
  padding-top: var(--spacing-md);
  border-top: 1px dashed var(--color-border);
}
.form-section__title {
  margin: var(--spacing-xs) 0 var(--spacing-md);
  font-size: 16px;
  font-weight: 500;
  color: var(--color-text-primary);
  font-family: var(--font-serif);
}
.advanced-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
  gap: var(--spacing-md);
}
.endpoint-row {
  display: grid;
  grid-template-columns: minmax(0, 1fr) auto;
  gap: var(--spacing-sm);
}
.endpoint-row__button {
  position: relative;
  min-width: calc(var(--ui-height-base) * 4);
}
.helper-text {
  margin-top: var(--spacing-xs);
  font-size: 13px;
  color: var(--color-text-secondary);
}
.api-key-status {
  font-weight: 500;
}
.test-status-row {
  display: flex;
  align-items: center;
  gap: var(--spacing-sm);
  flex-wrap: wrap;
}
.test-status-row__label {
  font-size: 14px;
  color: var(--color-text-secondary);
}
.test-status-row__message {
  font-size: 13px;
  color: var(--color-text-secondary);
}
.test-status-row__message--error {
  color: var(--color-error);
}
</style>
