// frontend/src/features/settings/components/LlmSettingsPanel.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useLlmSettings } from '../composables/useLlmSettings'
import { Input } from '@/shared/ui/input'
import { Button } from '@/shared/ui/button'
import {
  Combobox,
  ComboboxAnchor,
  ComboboxContent,
  ComboboxInput,
  ComboboxItem,
} from '@/shared/ui/combobox'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/shared/ui/select'
import { Eye, EyeOff, Trash2 } from '@lucide/vue'
import { FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/shared/ui/form'
import { useForm } from 'vee-validate'
import { toTypedSchema } from '@vee-validate/zod'
import { llmSettingsSchema } from '../model/llmSchema'
import { InlineAsyncError } from '@/shared/ui/inline-async-error'
import { Skeleton } from '@/shared/ui/skeleton'

const { draft, view, actions } = useLlmSettings()
const { selectedProviderKey, selectedModel, baseUrlInput, apiKeyInput, maxTokens, thinkingDepth } =
  draft
const {
  loading,
  error,
  saving,
  testing,
  discovering,
  providerOptions,
  apiKeyMasked,
  modelOptions,
  modelDiscoveryHint,
  isCustomProviderSelected,
  canDiscoverModels,
  endpointPlaceholder,
  endpointHint,
} = view
const {
  loadSettings,
  saveSettings,
  clearApiKey,
  testSettings,
  discoverModels,
  clearSensitiveDraft: clearSensitiveSettings,
} = actions

const showApiKey = ref(false)
const modelComboboxOpen = ref(false)
const modelCandidateIndex = ref(-1)

const { handleSubmit, setValues, submitCount } = useForm({
  validationSchema: toTypedSchema(llmSettingsSchema),
})

const apiKeyStatusLabel = computed(() =>
  apiKeyMasked.value ? `已保存：${apiKeyMasked.value}` : '未保存',
)
const canShowModelCombobox = computed(
  () => isCustomProviderSelected.value && modelOptions.value.length > 0,
)

function clearSensitiveDraft() {
  clearSensitiveSettings()
  showApiKey.value = false
  modelComboboxOpen.value = false
  modelCandidateIndex.value = -1
}

function selectModelCandidate(model: string) {
  selectedModel.value = model
  modelComboboxOpen.value = false
  modelCandidateIndex.value = -1
}

function moveModelCandidate(delta: number) {
  if (!canShowModelCombobox.value) {
    return
  }
  modelComboboxOpen.value = true
  const count = modelOptions.value.length
  if (count === 0) {
    return
  }
  if (modelCandidateIndex.value < 0) {
    modelCandidateIndex.value = delta > 0 ? 0 : count - 1
    return
  }
  modelCandidateIndex.value = (modelCandidateIndex.value + delta + count) % count
}

function selectHighlightedModelCandidate() {
  if (!modelComboboxOpen.value || !canShowModelCombobox.value) {
    return
  }
  const model = modelOptions.value[modelCandidateIndex.value]
  if (model) {
    selectModelCandidate(model)
  }
}

function handleModelCandidateKeydown(event: KeyboardEvent) {
  if (event.isComposing) {
    return
  }
  if (event.key === 'ArrowDown') {
    event.preventDefault()
    event.stopPropagation()
    moveModelCandidate(1)
    return
  }
  if (event.key === 'ArrowUp') {
    event.preventDefault()
    event.stopPropagation()
    moveModelCandidate(-1)
    return
  }
  if (event.key === 'Enter' && modelComboboxOpen.value) {
    event.preventDefault()
    event.stopPropagation()
    selectHighlightedModelCandidate()
    return
  }
  if (event.key === 'Escape') {
    event.preventDefault()
    event.stopPropagation()
    modelComboboxOpen.value = false
  }
}

watch(
  [selectedProviderKey, baseUrlInput, selectedModel, apiKeyInput, maxTokens, thinkingDepth],
  () => {
    setValues({
      providerKey: selectedProviderKey.value,
      baseUrl: baseUrlInput.value,
      model: selectedModel.value,
      apiKey: apiKeyInput.value,
      maxTokens: maxTokens.value,
      thinkingDepth: thinkingDepth.value,
    })
  },
  { immediate: true },
)

watch(canShowModelCombobox, (canShow) => {
  if (!canShow) {
    modelComboboxOpen.value = false
    modelCandidateIndex.value = -1
  }
})

watch(modelOptions, () => {
  modelCandidateIndex.value = -1
})

const onSubmit = handleSubmit(async () => {
  await saveSettings()
})

onMounted(() => {
  void loadSettings()
})

defineExpose({
  submit: onSubmit,
  test: testSettings,
  saving,
  testing,
  loading,
  clearSensitiveDraft,
})
</script>

<template>
  <div class="panel-content-wrapper">
    <div v-if="loading" class="llm-loading" aria-busy="true">
      <Skeleton />
      <Skeleton />
      <Skeleton class="llm-loading__large" />
    </div>
    <InlineAsyncError v-else-if="error" :message="error" @retry="loadSettings" />
    <form v-else class="flex flex-col gap-6" @submit.prevent="onSubmit">
      <div class="field-grid">
        <FormField name="providerKey">
          <FormItem>
            <FormLabel>接入方式</FormLabel>
            <Select
              :model-value="selectedProviderKey"
              @update:model-value="
                (value) => {
                  selectedProviderKey = String(value)
                }
              "
            >
              <SelectTrigger aria-label="接入方式">
                <SelectValue placeholder="请选择接入方式" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem
                  v-for="provider in providerOptions"
                  :key="provider.providerKey"
                  :value="provider.providerKey"
                >
                  {{ provider.displayName }}
                </SelectItem>
              </SelectContent>
            </Select>
            <FormMessage v-if="submitCount > 0" />
          </FormItem>
        </FormField>

        <FormField name="model" v-slot="{ componentField }">
          <FormItem>
            <FormLabel>模型</FormLabel>
            <Select
              v-if="!isCustomProviderSelected"
              :disabled="modelOptions.length === 0"
              :model-value="selectedModel"
              @update:model-value="
                (value) => {
                  selectedModel = String(value)
                }
              "
            >
              <SelectTrigger aria-label="模型">
                <SelectValue placeholder="请选择模型" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem v-for="model in modelOptions" :key="model" :value="model">
                  {{ model }}
                </SelectItem>
              </SelectContent>
            </Select>
            <template v-else>
              <Combobox
                v-model:open="modelComboboxOpen"
                :model-value="selectedModel"
                :open-on-focus="canShowModelCombobox"
                :open-on-click="canShowModelCombobox"
                :reset-search-term-on-select="false"
                ignore-filter
                @update:model-value="
                  (value) => {
                    selectModelCandidate(String(value))
                  }
                "
              >
                <ComboboxAnchor as-child>
                  <div class="model-combobox">
                    <FormControl>
                      <ComboboxInput
                        :model-value="selectedModel"
                        autocomplete="off"
                        placeholder="请选择模型"
                        @update:model-value="
                          (value) => {
                            selectedModel = String(value)
                          }
                        "
                        @blur="componentField.onBlur"
                        @keydown.capture="handleModelCandidateKeydown"
                      />
                    </FormControl>
                  </div>
                </ComboboxAnchor>
                <ComboboxContent
                  v-if="canShowModelCombobox"
                  data-byok-model-combobox-content
                  align="start"
                  side="bottom"
                  :side-offset="4"
                  @escape-key-down.prevent="modelComboboxOpen = false"
                >
                  <ComboboxItem
                    v-for="(model, index) in modelOptions"
                    :key="model"
                    :value="model"
                    :text-value="model"
                    :class="{ 'bg-accent text-accent-foreground': modelCandidateIndex === index }"
                    data-byok-model-combobox-item
                    @pointermove="modelCandidateIndex = index"
                  >
                    {{ model }}
                  </ComboboxItem>
                </ComboboxContent>
              </Combobox>
              <p v-if="modelDiscoveryHint" class="helper-text text-sm">{{ modelDiscoveryHint }}</p>
            </template>
            <FormMessage v-if="submitCount > 0" />
          </FormItem>
        </FormField>
      </div>

      <FormField v-if="isCustomProviderSelected" name="baseUrl" v-slot="{ componentField }">
        <FormItem>
          <FormLabel>Base URL</FormLabel>
          <div class="endpoint-row">
            <FormControl>
              <Input
                :model-value="baseUrlInput"
                autocomplete="off"
                :placeholder="endpointPlaceholder"
                @update:model-value="
                  (value) => {
                    baseUrlInput = String(value)
                  }
                "
                @blur="componentField.onBlur"
              />
            </FormControl>
            <Button
              v-if="canDiscoverModels"
              type="button"
              variant="secondary"
              class="endpoint-row__button"
              :disabled="discovering"
              :loading="discovering"
              @click="discoverModels"
            >
              检测模型
            </Button>
          </div>
          <p class="helper-text text-sm">{{ endpointHint }}</p>
          <FormMessage v-if="submitCount > 0" />
        </FormItem>
      </FormField>

      <FormField name="apiKey" v-slot="{ componentField }">
        <FormItem class="relative">
          <FormLabel>API Key</FormLabel>
          <div class="relative w-full flex items-center">
            <FormControl>
              <Input
                :model-value="apiKeyInput"
                autocomplete="off"
                placeholder="留空表示不修改当前 Key"
                :type="showApiKey ? 'text' : 'password'"
                class="pr-20"
                @update:model-value="
                  (value) => {
                    apiKeyInput = String(value)
                  }
                "
                @blur="componentField.onBlur"
              />
            </FormControl>
            <div class="absolute right-0 top-0 h-full flex items-center pr-1">
              <button
                v-if="apiKeyMasked"
                type="button"
                aria-label="清除 API Key"
                class="ui-action ui-action-danger border border-transparent px-2 py-2 text-muted-foreground transition-colors [transition-duration:var(--motion-duration-base)] [transition-timing-function:var(--motion-ease-standard)] hover:bg-transparent hover:text-destructive"
                @click="clearApiKey"
              >
                <Trash2 class="h-4 w-4" />
              </button>
              <button
                type="button"
                :aria-label="showApiKey ? '隐藏 API Key' : '显示 API Key'"
                class="ui-action ui-action-icon border border-transparent px-2 py-2 text-muted-foreground transition-colors [transition-duration:var(--motion-duration-base)] [transition-timing-function:var(--motion-ease-standard)] hover:bg-transparent"
                @click="showApiKey = !showApiKey"
              >
                <Eye v-if="showApiKey" class="h-4 w-4" />
                <EyeOff v-else class="h-4 w-4" />
              </button>
            </div>
          </div>
          <p class="helper-text api-key-status text-sm">{{ apiKeyStatusLabel }}</p>
          <FormMessage v-if="submitCount > 0" />
        </FormItem>
      </FormField>

      <div class="form-section">
        <div class="form-section__title">高级设置</div>
        <div class="advanced-grid">
          <FormField name="maxTokens">
            <FormItem>
              <FormLabel>最大回复长度 (Max Tokens)</FormLabel>
              <FormControl>
                <Select
                  :model-value="maxTokens ? String(maxTokens) : 'auto'"
                  @update:model-value="
                    (value) => {
                      maxTokens = value === 'auto' ? undefined : Number(value)
                    }
                  "
                >
                  <SelectTrigger class="w-full" aria-label="最大回复 Token">
                    <SelectValue placeholder="模型默认 (Auto)" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="auto">模型默认 (Auto)</SelectItem>
                    <SelectItem value="4096">常规 (4096)</SelectItem>
                    <SelectItem value="8192">长回复 (8192)</SelectItem>
                    <SelectItem value="32768">深度分析 (32768)</SelectItem>
                  </SelectContent>
                </Select>
              </FormControl>
              <FormMessage v-if="submitCount > 0" />
            </FormItem>
          </FormField>

          <FormField name="thinkingDepth">
            <FormItem>
              <FormLabel>思考深度 (Thinking Depth)</FormLabel>
              <Select
                :model-value="thinkingDepth || 'default'"
                @update:model-value="
                  (value) => {
                    thinkingDepth = String(value) === 'default' ? undefined : String(value)
                  }
                "
              >
                <SelectTrigger aria-label="思考深度">
                  <SelectValue placeholder="默认 (Default)" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="default">默认（Default）</SelectItem>
                  <SelectItem value="low">低 (Low)</SelectItem>
                  <SelectItem value="medium">中 (Medium)</SelectItem>
                  <SelectItem value="high">高 (High)</SelectItem>
                  <SelectItem value="xhigh">极高 (Extreme)</SelectItem>
                </SelectContent>
              </Select>
              <p class="helper-text text-sm">部分模型可能不支持，测试失败时请改回默认。</p>
              <FormMessage v-if="submitCount > 0" />
            </FormItem>
          </FormField>
        </div>
      </div>
    </form>
  </div>
</template>

<style scoped>
.panel-content-wrapper {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-md);
  font-family: var(--font-serif);
}

.llm-loading {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-md);
}

.llm-loading > * {
  min-block-size: var(--ui-height-md);
}

.llm-loading__large {
  min-block-size: calc(var(--layout-settings-dialog-min-block-size) / 2);
}
.form-section {
  margin-top: var(--spacing-md);
  padding-top: var(--spacing-md);
  border-top: 1px dashed var(--color-border);
}
.form-section__title {
  margin: var(--spacing-xs) 0 var(--spacing-md);
  font-size: var(--font-size-md);
  font-weight: 500;
  color: var(--color-text-primary);
  font-family: var(--font-serif);
}
.advanced-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(var(--layout-form-field-min-inline-size), 1fr));
  gap: var(--spacing-md);
}
.endpoint-row {
  display: grid;
  grid-template-columns: minmax(0, 1fr) auto;
  gap: var(--spacing-sm);
}
.endpoint-row__button {
  position: relative;
}
.helper-text {
  margin-top: var(--spacing-xs);
  color: var(--color-text-secondary);
}
.api-key-status {
  font-weight: 500;
}
.model-combobox {
  width: 100%;
}
</style>

// frontend/src/features/settings/LlmSettingsPanel.tsx
import { Eye, EyeOff, RefreshCw, Trash2 } from 'lucide-react'
import { useQuery } from '@tanstack/react-query'
import { Button, Field, IconTooltip, Input, Select } from '@/shared/ui'
import { useLlmSettings } from './useLlmSettings'
import { fetchLlmConfig, fetchProviders } from './api'

export function LlmSettingsPanel({ providerKey }: { providerKey?: string }) {
  const config = useQuery({ queryKey: ['llm-config'], queryFn: fetchLlmConfig })
  const providers = useQuery({ queryKey: ['llm-providers'], queryFn: fetchProviders })
  if (config.isPending || providers.isPending)
    return <div className="empty-state">正在读取模型配置…</div>
  const error = config.error || providers.error
  if (error || !config.data || !providers.data)
    return <div className="empty-state">{error?.message ?? '模型配置不可用'}</div>
  return (
    <LlmSettingsForm
      key={`${providerKey ?? config.data.providerKey}:${config.data.baseUrl}:${config.data.model}`}
      config={config.data}
      providers={providers.data}
      providerKey={providerKey}
    />
  )
}

function LlmSettingsForm({
  config,
  providers,
  providerKey,
}: {
  config: Awaited<ReturnType<typeof fetchLlmConfig>>
  providers: Awaited<ReturnType<typeof fetchProviders>>
  providerKey?: string
}) {
  const state = useLlmSettings(config, providers, providerKey)
  const endpointHint = state.protocol
    ? `填写接口根地址，系统会请求 ${state.protocol.endpointSuffix}。`
    : 'DeepSeek 使用系统配置的服务地址。'
  return (
    <div className="panel-content-wrapper">
      <Field label="服务协议" htmlFor="llm-provider">
        <Select
          id="llm-provider"
          value={state.draft.providerKey}
          options={state.providers.map((provider) => ({
            value: provider.providerKey,
            label: provider.displayName,
          }))}
          onValueChange={state.selectProvider}
        />
      </Field>
      {state.custom && (
        <Field label="Base URL" htmlFor="llm-base-url" hint={endpointHint}>
          <div className="endpoint-row">
            <Input
              id="llm-base-url"
              value={state.draft.baseUrl ?? ''}
              placeholder={state.protocol?.placeholder}
              onChange={(event) => state.update('baseUrl', event.target.value)}
            />
            {state.protocol?.modelDiscovery && (
              <Button
                type="button"
                variant="secondary"
                loading={state.discovering}
                onClick={state.discover}
              >
                <RefreshCw size={15} />
                检测模型
              </Button>
            )}
          </div>
        </Field>
      )}
      <Field label="模型" htmlFor="llm-model">
        {state.models.length ? (
          <Select
            id="llm-model"
            value={state.draft.model}
            options={[...new Set([state.draft.model, ...state.models])]
              .filter(Boolean)
              .map((model) => ({ value: model, label: model }))}
            onValueChange={(value) => state.update('model', value)}
          />
        ) : (
          <Input
            id="llm-model"
            value={state.draft.model}
            placeholder="输入模型 ID"
            onChange={(event) => state.update('model', event.target.value)}
          />
        )}
      </Field>
      <Field
        label="API Key"
        htmlFor="llm-api-key"
        hint={
          state.config?.hasApiKey && state.config.apiKeyMasked
            ? `已保存 ${state.config.apiKeyMasked}`
            : undefined
        }
      >
        <div className="password-field">
          <Input
            id="llm-api-key"
            type={state.showKey ? 'text' : 'password'}
            autoComplete="off"
            value={state.draft.apiKey ?? ''}
            placeholder="留空表示保留当前 Key"
            onChange={(event) => state.update('apiKey', event.target.value)}
          />
          <div className="password-field__actions">
            {state.config?.hasApiKey && (
              <IconTooltip label="清除已保存的 API Key">
                <button
                  className="password-toggle ui-action ui-action-icon"
                  type="button"
                  aria-label="清除已保存的 API Key"
                  onClick={() => state.update('apiKey', '__CLEAR__')}
                >
                  <Trash2 size={16} />
                </button>
              </IconTooltip>
            )}
            <IconTooltip label={state.showKey ? '隐藏 API Key' : '显示 API Key'}>
              <button
                className="password-toggle ui-action ui-action-icon"
                type="button"
                aria-label={state.showKey ? '隐藏 API Key' : '显示 API Key'}
                onClick={() => state.setShowKey(!state.showKey)}
              >
                {state.showKey ? <Eye size={16} /> : <EyeOff size={16} />}
              </button>
            </IconTooltip>
          </div>
        </div>
      </Field>
      <section className="settings-form-section">
        <h3 className="settings-form-section__title">高级设置</h3>
        <div className="advanced-grid">
          <Field label="最大回复长度" htmlFor="llm-max-tokens">
            <Select
              id="llm-max-tokens"
              value={state.draft.maxTokens ? String(state.draft.maxTokens) : ''}
              options={[
                { value: '', label: '模型默认' },
                { value: '4096', label: '常规 (4096)' },
                { value: '8192', label: '长回复 (8192)' },
                { value: '32768', label: '深度分析 (32768)' },
              ]}
              onValueChange={(value) =>
                state.update('maxTokens', value ? Number(value) : undefined)
              }
            />
          </Field>
          <Field label="思考深度" htmlFor="llm-thinking-depth">
            <Select
              id="llm-thinking-depth"
              value={state.draft.thinkingDepth ?? ''}
              options={[
                { value: '', label: '默认' },
                { value: 'low', label: '低' },
                { value: 'medium', label: '中' },
                { value: 'high', label: '高' },
                { value: 'xhigh', label: '极高' },
              ]}
              onValueChange={(value) => state.update('thinkingDepth', value || null)}
            />
          </Field>
        </div>
      </section>
      {state.testMessage && (
        <p className="helper-text" role="status">
          {state.testMessage}
        </p>
      )}
      <div className="settings-inline-actions settings-inline-actions--header">
        <Button
          variant="secondary"
          loading={state.testing}
          disabled={state.saving}
          onClick={state.test}
        >
          测试连接
        </Button>
        <Button loading={state.saving} disabled={state.testing} onClick={state.save}>
          保存设置
        </Button>
      </div>
    </div>
  )
}
