// frontend/src/components/workspace/MessageThread.vue
<script setup lang="ts">
import { computed, nextTick, onMounted, ref, watch } from 'vue'
import { ElTag } from 'element-plus'
import type { InterviewMessageRecord, InterviewMessageRole } from '../../api/contracts'

const props = defineProps<{
  messages: InterviewMessageRecord[]
  reconnectingStatus?: string
}>()

const threadRef = ref<HTMLElement | null>(null)

const displayMessages = computed(() => {
  return props.messages
    .filter(m => m.role !== 'system')
    .map(m => ({
      ...m,
      content: m.content
        ? m.content
            .replace(/\[STAGE[_\s]?COMPLETE\]?/g, '')
            .replace(/\[STAGE(?:_(?:COM(?:P(?:L(?:E(?:TE?)?)?)?)?)?)?$/, '')
        : ''
    }))
})

let scrollRafId: number | null = null

watch(() => props.messages, () => {
  if (scrollRafId != null) {
    cancelAnimationFrame(scrollRafId)
  }
  nextTick(() => {
    scrollRafId = requestAnimationFrame(() => {
      scrollRafId = null
      if (threadRef.value) {
        threadRef.value.scrollTop = threadRef.value.scrollHeight
      }
    })
  })
}, { deep: true })

onMounted(() => {
  nextTick(() => {
    requestAnimationFrame(() => {
      if (threadRef.value) {
        threadRef.value.scrollTop = threadRef.value.scrollHeight
      }
    })
  })
})
</script>

<template>
  <div class="message-thread scrollable" ref="threadRef">
    <div v-if="!displayMessages.length" class="message-thread__empty">
      <p class="message-thread__empty-copy">会话已准备就绪，可以开始面试了。</p>
    </div>

    <template v-else>
      <article
        v-for="message in displayMessages"
        :key="`${message.id}-${message.createdAt}`"
        :class="['message-bubble', `message-bubble--${message.role as InterviewMessageRole}`]"
      >
        <div class="message-bubble__head">
          <ElTag class="ui-badge" effect="light">
            {{ message.role === 'assistant' ? '面试官' : '我' }}
          </ElTag>
        </div>
        <div class="message-bubble__content">
          <span v-if="message.role === 'assistant' && !message.content" class="thinking-dots">思考中</span>
          <span v-else>{{ message.content }}</span>
        </div>
      </article>

      <div v-if="reconnectingStatus" class="reconnecting-status">
        {{ reconnectingStatus }}
      </div>
    </template>
  </div>
</template>

<style scoped>
.message-thread {
  flex: 1;
  overflow-y: auto;
  padding: var(--spacing-lg) var(--spacing-2xl) var(--composer-height);
  display: flex;
  flex-direction: column;
  gap: 24px;
  min-height: 0;
}
.message-thread__empty {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100%;
  color: var(--color-text-tertiary);
}
.message-bubble {
  display: flex;
  flex-direction: column;
  gap: 8px;
  max-width: min(80%, 760px);
}
.message-bubble--user {
  align-self: flex-end;
  align-items: flex-end;
}
.message-bubble--assistant {
  align-self: flex-start;
  align-items: flex-start;
}
.message-bubble__content {
  padding: 12px 16px;
  border-radius: var(--radius-lg);
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  line-height: 1.6;
  white-space: pre-wrap;
  word-break: break-word;
  box-shadow: var(--shadow-whisper);
}
.message-bubble--user .message-bubble__content {
  background: color-mix(in srgb, var(--color-brand) 8%, var(--color-surface));
  border-color: color-mix(in srgb, var(--color-brand) 20%, var(--color-border));
  border-top-right-radius: 4px;
}
.message-bubble--assistant .message-bubble__content {
  border-top-left-radius: 4px;
}
.thinking-dots {
  color: var(--color-text-tertiary);
}
.thinking-dots::after {
  content: '';
  animation: thinking-ellipsis 1.5s infinite;
}
@keyframes thinking-ellipsis {
  0% { content: '.'; }
  33% { content: '..'; }
  66% { content: '...'; }
}
.reconnecting-status {
  align-self: center;
  padding: 8px 16px;
  background: var(--color-surface);
  border: 1px dashed var(--color-border);
  border-radius: var(--radius-lg);
  color: var(--color-text-secondary);
  font-size: 13px;
  box-shadow: var(--shadow-whisper);
  margin-top: 8px;
}
.reconnecting-status::after {
  content: '';
  animation: thinking-ellipsis 1.5s infinite;
}
</style>

// frontend/src/features/interview/components/MessageThread.tsx
import { useEffect, useRef } from 'react'
import { cn } from '@/shared/lib/cn'
import type { InterviewMessageRecord } from '../types'

export function MessageThread({ messages }: { messages: InterviewMessageRecord[] }) {
  const thread = useRef<HTMLDivElement>(null)
  const visible = messages
    .filter((message) => message.role !== 'system')
    .map((message) => ({
      ...message,
      content:
        message.content
          ?.replace(/\[STAGE[_\s]?COMPLETE\]?/g, '')
          .replace(/\[STAGE(?:_(?:COM(?:P(?:L(?:E(?:TE?)?)?)?)?)?)?$/, '') ?? '',
    }))
  useEffect(() => {
    const frame = requestAnimationFrame(() => {
      if (thread.current) thread.current.scrollTop = thread.current.scrollHeight
    })
    return () => cancelAnimationFrame(frame)
  }, [messages])
  return (
    <div
      className="scrollable gutter-stable flex min-h-0 flex-1 flex-col gap-lg overflow-y-auto px-2xl pt-lg pb-(--composer-height)"
      ref={thread}
      data-slot="message-thread"
    >
      {visible.length ? (
        visible.map((message, index) => (
          <article
            className={cn(
              'message-bubble',
              message.role === 'user' ? 'items-end self-end' : 'items-start self-start',
            )}
            key={`${message.id}-${message.createdAt ?? index}`}
          >
            {/* Per-answer score and coaching belong to the finished report; the live
                thread only says who is speaking. */}
            <div className="flex w-full items-center gap-sm">
              <span
                className={cn(
                  'font-serif text-xs text-text-tertiary',
                  message.role === 'user' && 'ms-auto',
                )}
              >
                {message.role === 'assistant' ? '面试官' : '我'}
              </span>
            </div>
            <div
              className={cn(
                'message-bubble-body',
                message.role === 'user'
                  ? 'rounded-lg rounded-se-sm bg-surface-muted'
                  : 'rounded-lg rounded-ss-sm bg-surface elevated-whisper',
              )}
            >
              {message.role === 'assistant' && !message.content ? (
                <span className="ellipsis-progress text-text-tertiary">思考中</span>
              ) : (
                message.content
              )}
            </div>
          </article>
        ))
      ) : (
        <div className="flex h-full items-center justify-center text-text-tertiary">
          <p>会话已准备就绪，可以开始面试了。</p>
        </div>
      )}
    </div>
  )
}
