// frontend/src/features/insight/pages/AnalyticsPage.vue
<script setup lang="ts">
import { LineChart, RadarChart } from 'echarts/charts'
import { GridComponent, RadarComponent, TooltipComponent } from 'echarts/components'
import { init, use, type ECharts } from 'echarts/core'
import { CanvasRenderer } from 'echarts/renderers'
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { fetchRadarAnalytics, fetchTrendAnalytics, fetchWeaknessAnalytics } from '../api/analytics'
import { getErrorMessage } from '@/shared/lib/errors'
import type {
  AnalyticsRadarResponse,
  AnalyticsTrendPoint,
  AnalyticsWeaknessItem,
} from '../model/types'
import { usePageNotice } from '@/shared/ui/sonner/usePageNotice'
import { Card } from '@/shared/ui/card'
import { Badge } from '@/shared/ui/badge'
import EmptyState from '@/shared/ui/empty-state/EmptyState.vue'

const { showNotice } = usePageNotice()

use([LineChart, RadarChart, GridComponent, RadarComponent, TooltipComponent, CanvasRenderer])

const radar = ref<AnalyticsRadarResponse | null>(null)
const trend = ref<AnalyticsTrendPoint[]>([])
const weaknesses = ref<AnalyticsWeaknessItem[]>([])
const radarRef = ref<HTMLDivElement | null>(null)
const trendRef = ref<HTMLDivElement | null>(null)
let radarChart: ECharts | null = null
let trendChart: ECharts | null = null

const scoreCards = computed(() => {
  if (!radar.value || radar.value.sessionCount === 0) {
    return []
  }

  return [
    { label: '技术能力', value: radar.value.technical.toFixed(1), hint: '最近 5 场均分' },
    { label: '表达清晰度', value: radar.value.expression.toFixed(1), hint: '最近 5 场均分' },
    { label: '逻辑思维', value: radar.value.logic.toFixed(1), hint: '最近 5 场均分' },
  ]
})

function normalizeChartColor(value: string) {
  const srgbMatch = value.match(/^color\(srgb\s+([0-9.]+)\s+([0-9.]+)\s+([0-9.]+)/)
  if (!srgbMatch) return value
  const [, r, g, b] = srgbMatch
  return `rgb(${Math.round(Number(r) * 255)}, ${Math.round(Number(g) * 255)}, ${Math.round(Number(b) * 255)})`
}

function resolveChartColor(value: string) {
  const probe = document.createElement('span')
  probe.style.color = value
  document.body.appendChild(probe)
  const computed = getComputedStyle(probe).color
  probe.remove()
  return normalizeChartColor(computed || value)
}

function cssVar(name: string, fallback: string) {
  const value = getComputedStyle(document.documentElement).getPropertyValue(name).trim()
  return resolveChartColor(value || fallback)
}

function cssVarNumber(name: string, fallback: number) {
  const value = getComputedStyle(document.documentElement).getPropertyValue(name).trim()
  const parsed = Number.parseFloat(value)
  return Number.isFinite(parsed) ? parsed : fallback
}

function cssDeclarations(declarations: Record<string, string>) {
  return Object.entries(declarations)
    .map(([property, value]) => `${property}: ${value}`)
    .join('; ')
}

function formatDate(dateString: string, format: 'MM/DD' | 'YYYY/MM/DD') {
  const d = new Date(dateString)
  const yyyy = d.getFullYear()
  const mm = String(d.getMonth() + 1).padStart(2, '0')
  const dd = String(d.getDate()).padStart(2, '0')
  if (format === 'MM/DD') return `${mm}/${dd}`
  return `${yyyy}/${mm}/${dd}`
}

async function loadAnalytics() {
  try {
    const [radarData, trendData, weaknessData] = await Promise.all([
      fetchRadarAnalytics(),
      fetchTrendAnalytics(),
      fetchWeaknessAnalytics(),
    ])
    radar.value = radarData
    trend.value = trendData
    weaknesses.value = weaknessData
    await nextTick()
    renderCharts()
  } catch (error) {
    showNotice(getErrorMessage(error), 'error')
  }
}

function renderCharts() {
  const brand = cssVar('--chart-technical', 'var(--color-brand)')
  const coral = cssVar('--chart-expression', 'var(--color-coral)')
  const logic = cssVar('--chart-logic', 'var(--color-ring-deep)')
  const secondary = cssVar('--color-text-secondary', 'var(--color-text-secondary)')
  const lineDecor = cssVar('--color-border-warm', 'var(--color-border-warm)')
  const ring = cssVar('--color-ring', 'var(--color-ring)')
  const tooltipSurface = cssVar('--color-surface', 'var(--color-surface)')
  const tooltipBorder = cssVar('--color-input', 'var(--color-input)')
  const tooltipText = cssVar('--color-text-primary', 'var(--color-text-primary)')
  const tooltipFontFamily = getComputedStyle(document.documentElement)
    .getPropertyValue('--font-serif')
    .trim()

  if (radar.value && radarRef.value && radar.value.sessionCount > 0) {
    radarChart ??= init(radarRef.value)
    radarChart.setOption({
      animation: false,
      radar: {
        radius: '64%',
        splitNumber: 5,
        axisName: { color: secondary, fontSize: cssVarNumber('--font-size-sm', 14) },
        splitLine: { lineStyle: { color: lineDecor } },
        splitArea: { show: false },
        axisLine: { lineStyle: { color: ring } },
        indicator: [
          { name: '技术能力', max: 10 },
          { name: '表达清晰度', max: 10 },
          { name: '逻辑思维', max: 10 },
        ],
      },
      series: [
        {
          type: 'radar',
          data: [
            {
              value: [radar.value.technical, radar.value.expression, radar.value.logic],
              areaStyle: { color: brand, opacity: 0.16 },
              lineStyle: { color: brand, width: 2 },
              itemStyle: { color: brand },
            },
          ],
        },
      ],
    })
  }

  if (trendRef.value && trend.value.length > 0) {
    trendChart ??= init(trendRef.value)
    trendChart.setOption({
      animation: false,
      tooltip: {
        trigger: 'axis',
        className: 'ui-chart-tooltip',
        backgroundColor: tooltipSurface,
        borderColor: tooltipBorder,
        borderWidth: 1,
        padding: [cssVarNumber('--spacing-xs', 4), cssVarNumber('--spacing-sm', 8)],
        textStyle: {
          color: tooltipText,
          fontFamily: tooltipFontFamily,
          fontSize: cssVarNumber('--font-size-sm', 14),
        },
        extraCssText: cssDeclarations({
          'border-radius': 'var(--radius-md)',
          'box-shadow': 'var(--shadow-whisper)',
        }),
        formatter: (params: any) => {
          if (!params || !params.length) return ''
          const dataIndex = params[0].dataIndex
          const originalDate = trend.value[dataIndex].createdAt
          let html = `<div>${formatDate(originalDate, 'YYYY/MM/DD')}</div>`
          for (const param of params) {
            html += `<div>${param.marker} ${param.seriesName}: ${param.value}</div>`
          }
          return html
        },
      },
      grid: {
        left: cssVarNumber('--analytics-chart-grid-left', 44),
        right: cssVarNumber('--analytics-chart-grid-right', 18),
        top: cssVarNumber('--analytics-chart-grid-top', 30),
        bottom: cssVarNumber('--analytics-chart-grid-bottom', 30),
      },
      xAxis: {
        type: 'category',
        boundaryGap: false,
        data: trend.value.map((item) => formatDate(item.createdAt, 'MM/DD')),
        axisLine: { lineStyle: { color: ring } },
        axisLabel: { color: secondary },
      },
      yAxis: {
        type: 'value',
        min: 0,
        max: 10,
        splitLine: { lineStyle: { color: lineDecor } },
        axisLabel: { color: secondary },
      },
      series: [
        {
          name: '技术能力',
          type: 'line',
          smooth: true,
          data: trend.value.map((item) => item.technical),
          lineStyle: { color: brand, width: 2 },
          itemStyle: { color: brand },
        },
        {
          name: '表达清晰度',
          type: 'line',
          smooth: true,
          data: trend.value.map((item) => item.expression),
          lineStyle: { color: coral, width: 2 },
          itemStyle: { color: coral },
        },
        {
          name: '逻辑思维',
          type: 'line',
          smooth: true,
          data: trend.value.map((item) => item.logic),
          lineStyle: { color: logic, width: 2 },
          itemStyle: { color: logic },
        },
      ],
    })
  }
}

function handleResize() {
  radarChart?.resize()
  trendChart?.resize()
}

async function handleThemeChange() {
  await nextTick()
  renderCharts()
  handleResize()
}

watch([radar, trend], async () => {
  await nextTick()
  renderCharts()
})

onMounted(() => {
  window.addEventListener('resize', handleResize)
  window.addEventListener('prelude-theme-change', handleThemeChange)
  void loadAnalytics()
})

onBeforeUnmount(() => {
  window.removeEventListener('resize', handleResize)
  window.removeEventListener('prelude-theme-change', handleThemeChange)
  radarChart?.dispose()
  trendChart?.dispose()
})
</script>

<template>
  <section class="workspace-page">
    <header class="workspace-header">
      <div class="workspace-header__main">
        <div class="workspace-header__title-area">
          <h2 class="workspace-header__title">数据看板</h2>
        </div>
      </div>
    </header>

    <div class="workspace-page__content scrollable flex flex-col gap-6">
      <template v-if="radar && radar.sessionCount > 0">
        <div class="insight-strip insight-strip--compact">
          <article v-for="item in scoreCards" :key="item.label" class="insight-card">
            <p class="panel__eyebrow">{{ item.label }}</p>
            <h3 class="insight-card__value">{{ item.value }}</h3>
            <p class="insight-card__meta">{{ item.hint }}</p>
          </article>
        </div>

        <div class="page-grid page-grid--dashboard">
          <Card class="flex flex-col border-none shadow-none bg-surface p-5 rounded-xl">
            <div class="flex justify-between items-start mb-4">
              <div>
                <p class="text-xs text-muted-foreground uppercase tracking-wider mb-1">结构</p>
                <h3 class="text-lg font-medium font-serif">能力雷达</h3>
                <p class="text-sm text-muted-foreground">
                  展示最近面试在三项核心维度上的平均水平。
                </p>
              </div>
              <Badge variant="secondary">{{ radar.sessionCount }} 场</Badge>
            </div>
            <div ref="radarRef" class="chart-surface chart-surface--tall analytics-chart" />
          </Card>

          <Card class="flex flex-col border-none shadow-none bg-surface p-5 rounded-xl">
            <div class="flex justify-between items-start mb-4">
              <div>
                <p class="text-xs text-muted-foreground uppercase tracking-wider mb-1">走势</p>
                <h3 class="text-lg font-medium font-serif">分数趋势</h3>
                <p class="text-sm text-muted-foreground">按时间查看技术、表达与逻辑评分变化。</p>
              </div>
            </div>
            <div ref="trendRef" class="chart-surface chart-surface--tall analytics-chart" />
          </Card>
        </div>

        <div class="page-grid page-grid--single">
          <Card class="flex flex-col border-none shadow-none bg-surface p-5 rounded-xl">
            <div class="flex justify-between items-start mb-4">
              <div>
                <p class="text-xs text-muted-foreground uppercase tracking-wider mb-1">聚合</p>
                <h3 class="text-lg font-medium font-serif">薄弱点列表</h3>
                <p class="text-sm text-muted-foreground">按出现频率汇总薄弱点。</p>
              </div>
              <Badge variant="secondary">{{ weaknesses.length }} 类问题</Badge>
            </div>

            <div v-if="weaknesses.length" class="weakness-list">
              <article v-for="item in weaknesses" :key="item.category" class="weakness-item">
                <div class="weakness-item__head">
                  <div>
                    <h4 class="weakness-item__title">{{ item.category }}</h4>
                  </div>
                  <Badge variant="secondary">{{ item.count }} 次</Badge>
                </div>
                <ul class="weakness-item__descriptions">
                  <li v-for="description in item.descriptions" :key="description">
                    {{ description }}
                  </li>
                </ul>
              </article>
            </div>
            <EmptyState v-else description="还没有可聚合的薄弱点。" />
          </Card>
        </div>
      </template>

      <Card v-else class="flex flex-col border-none shadow-none bg-surface p-5 rounded-xl">
        <EmptyState description="暂无历史面试数据，完成至少一场面试后再回来查看。" />
      </Card>
    </div>
  </section>
</template>

<style scoped>
.page-grid--dashboard {
  /* ECharts grid 与图表块尺寸的局部语义变量，从此处读出。 */
  --analytics-chart-block-size: 256px;
  --analytics-chart-grid-left: 44;
  --analytics-chart-grid-right: 18;
  --analytics-chart-grid-top: 30;
  --analytics-chart-grid-bottom: 30;

  display: grid;
  grid-template-columns: repeat(
    auto-fit,
    minmax(var(--layout-dashboard-card-min-inline-size), 1fr)
  );
  gap: var(--spacing-lg);
}
.analytics-chart {
  block-size: var(--analytics-chart-block-size);
}
.weakness-list {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-md);
  margin-top: var(--spacing-md);
}
.weakness-item {
  padding: var(--spacing-sm);
  border-radius: var(--radius-lg);
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  page-break-inside: avoid;
  break-inside: avoid;
}
.weakness-item__head {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: var(--spacing-sm);
}
.weakness-item__title {
  margin: 0 0 var(--spacing-xs) 0;
  font-size: var(--font-size-md);
  font-weight: 500;
  color: var(--color-text-primary);
}
.weakness-item__summary {
  margin: 0;
  font-size: var(--font-size-xs);
  color: var(--color-text-secondary);
}
.weakness-item__descriptions {
  margin: 0;
  padding-left: var(--spacing-xl);
  font-size: var(--font-size-meta);
  color: var(--color-text-tertiary);
  list-style-type: disc;
}
.weakness-item__descriptions li {
  margin-bottom: var(--spacing-xs);
  line-height: 1.5;
}
</style>

// frontend/src/features/analytics/AnalyticsPage.tsx
import { useEffect, useRef } from 'react'
import { useQuery } from '@tanstack/react-query'
import * as echarts from 'echarts/core'
import { LineChart, RadarChart } from 'echarts/charts'
import {
  GridComponent,
  LegendComponent,
  RadarComponent,
  TooltipComponent,
} from 'echarts/components'
import { CanvasRenderer } from 'echarts/renderers'
import { RefreshCw } from 'lucide-react'
import { Button } from '@/shared/ui/button'
import { Panel } from '@/shared/ui/panel'
import { fetchRadar, fetchTrend, fetchWeaknesses } from './api'
import type { AnalyticsRadarResponse, AnalyticsTrendPoint } from './types'

echarts.use([
  LineChart,
  RadarChart,
  GridComponent,
  LegendComponent,
  RadarComponent,
  TooltipComponent,
  CanvasRenderer,
])

const TREND_GRID = {
  left: 44,
  right: 18,
  top: 30,
  bottom: 48,
} as const

export function AnalyticsPage() {
  const radar = useQuery({ queryKey: ['analytics-radar'], queryFn: fetchRadar })
  const trend = useQuery({ queryKey: ['analytics-trend'], queryFn: fetchTrend })
  const weaknesses = useQuery({ queryKey: ['analytics-weaknesses'], queryFn: fetchWeaknesses })
  const pending = radar.isPending || trend.isPending || weaknesses.isPending
  const error = radar.error || trend.error || weaknesses.error
  const cards = radar.data
    ? ([
        ['技术能力', radar.data.technical],
        ['表达清晰度', radar.data.expression],
        ['逻辑思维', radar.data.logic],
      ] as const)
    : []
  function reload() {
    void Promise.all([radar.refetch(), trend.refetch(), weaknesses.refetch()])
  }
  return (
    <section className="workspace-page">
      <header className="workspace-header">
        <div className="workspace-header__main">
          <div className="workspace-header__title-area">
            <h1 className="workspace-header__title">数据看板</h1>
          </div>
        </div>
      </header>
      <div className="workspace-page__content scrollable">
        {pending ? (
          <div className="empty-state" aria-live="polite">
            正在整理训练数据…
          </div>
        ) : error ? (
          <div className="empty-state">
            <p>{error.message}</p>
            <Button variant="secondary" onClick={reload}>
              <RefreshCw />
              重新加载
            </Button>
          </div>
        ) : !radar.data?.sessionCount ? (
          <div className="empty-state">
            <p>完成至少一场面试后，这里会显示能力变化与训练重点。</p>
          </div>
        ) : (
          <>
            <div className="grid grid-cols-3 gap-md">
              {cards.map(([label, value]) => (
                <article
                  className="grid gap-sm rounded-lg border border-border bg-surface p-lg elevated-whisper"
                  key={label}
                  data-slot="score-card"
                >
                  <p className="type-label" data-slot="score-label">
                    {label}
                  </p>
                  <strong className="type-metric" data-slot="score-value">
                    {value.toFixed(1)}
                  </strong>
                  <p className="type-meta" data-slot="score-meta">
                    最近 {radar.data.sessionCount} 场均分
                  </p>
                </article>
              ))}
            </div>
            <div className="grid grid-cols-2 gap-lg" data-slot="chart-grid">
              <Panel
                layout="card"
                eyebrow="结构"
                title="能力雷达"
                actions={<span className="type-meta shrink-0">{radar.data.sessionCount} 场</span>}
              >
                <p className="type-body max-w-(--layout-lead-max-inline-size)">
                  展示最近面试在三项核心维度上的平均水平。
                </p>
                <Radar data={radar.data} />
              </Panel>
              <Panel layout="card" eyebrow="走势" title="分数趋势">
                <p className="type-body max-w-(--layout-lead-max-inline-size)">
                  按时间查看技术、表达与逻辑评分变化。
                </p>
                <Trend data={trend.data ?? []} />
              </Panel>
            </div>
            <Panel
              layout="card"
              eyebrow="聚合"
              title="薄弱点列表"
              actions={
                <span className="type-meta shrink-0">{weaknesses.data?.length ?? 0} 类问题</span>
              }
            >
              <p className="type-body max-w-(--layout-lead-max-inline-size)">
                按出现频率汇总薄弱点。
              </p>
              {weaknesses.data?.length ? (
                weaknesses.data.map((item) => (
                  <article
                    className="grid gap-sm rounded-lg border border-border bg-surface-muted p-md break-inside-avoid"
                    data-slot="weakness-item"
                    key={item.category}
                  >
                    <div className="label-end-grid items-baseline gap-md">
                      <h3 className="type-subtitle" data-slot="weakness-title">
                        {item.category}
                      </h3>
                      <p className="type-meta" data-slot="weakness-summary">
                        出现 {item.count} 次
                      </p>
                    </div>
                    <ul
                      className="type-meta grid gap-xs list-plain"
                      data-slot="weakness-descriptions"
                    >
                      {item.descriptions.map((description) => (
                        <li key={description}>{description}</li>
                      ))}
                    </ul>
                  </article>
                ))
              ) : (
                <div className="empty-state">暂无已归纳的薄弱点。</div>
              )}
            </Panel>
          </>
        )}
      </div>
    </section>
  )
}

function useChart(createOption: () => echarts.EChartsCoreOption, dependency: unknown) {
  const element = useRef<HTMLDivElement>(null)
  const createOptionRef = useRef(createOption)
  const chartRef = useRef<echarts.ECharts | null>(null)

  useEffect(() => {
    createOptionRef.current = createOption
  }, [createOption])

  useEffect(() => {
    if (!element.current) return
    const chart = echarts.init(element.current)
    chartRef.current = chart
    const render = () => {
      chart.setOption(createOptionRef.current(), true)
      chart.resize()
    }
    render()
    const observer = new ResizeObserver(() => chart.resize())
    observer.observe(element.current)
    window.addEventListener('prelude-theme-change', render)
    return () => {
      window.removeEventListener('prelude-theme-change', render)
      observer.disconnect()
      chart.dispose()
      chartRef.current = null
    }
  }, [])

  useEffect(() => {
    chartRef.current?.setOption(createOptionRef.current(), true)
  }, [dependency])
  return element
}

function Radar({ data }: { data: AnalyticsRadarResponse }) {
  const ref = useChart(() => {
    const brand = cssVar('--chart-technical', 'var(--color-brand)')
    const secondary = cssVar('--color-text-secondary', 'var(--color-text-secondary)')
    const border = cssVar('--color-border-warm', 'var(--color-border)')
    const ring = cssVar('--color-ring', 'var(--color-border)')
    const serif = cssToken('--font-serif', 'serif')
    return {
      animation: false,
      radar: {
        radius: '64%',
        splitNumber: 5,
        indicator: [
          { name: '技术能力', max: 10 },
          { name: '表达清晰度', max: 10 },
          { name: '逻辑思维', max: 10 },
        ],
        splitArea: { show: false },
        axisName: {
          color: secondary,
          fontFamily: serif,
          fontSize: cssVarNumber('--font-size-sm', 14),
          fontWeight: 500,
        },
        splitLine: { lineStyle: { color: border } },
        axisLine: { lineStyle: { color: ring } },
      },
      series: [
        {
          type: 'radar',
          data: [
            {
              value: [data.technical, data.expression, data.logic],
              areaStyle: { color: brand, opacity: 0.16 },
              lineStyle: { color: brand, width: 2 },
              itemStyle: { color: brand },
            },
          ],
        },
      ],
    }
  }, data)
  return (
    <div
      className="h-(--layout-chart-block-size) min-h-(--layout-chart-block-size)"
      ref={ref}
      role="img"
      aria-label={`技术能力 ${data.technical}，表达清晰度 ${data.expression}，逻辑思维 ${data.logic}`}
    />
  )
}

function Trend({ data }: { data: AnalyticsTrendPoint[] }) {
  const ref = useChart(() => {
    const technical = cssVar('--chart-technical', 'var(--color-brand)')
    const expression = cssVar('--chart-expression', 'var(--color-coral)')
    const logic = cssVar('--chart-logic', 'var(--color-ring-deep)')
    const secondary = cssVar('--color-text-secondary', 'var(--color-text-secondary)')
    const tertiary = cssVar('--color-text-tertiary', 'var(--color-text-tertiary)')
    const border = cssVar('--color-border-warm', 'var(--color-border)')
    const ring = cssVar('--color-ring', 'var(--color-border)')
    const surface = cssVar('--color-surface', 'var(--color-bg)')
    const input = cssVar('--color-input', 'var(--color-border)')
    const text = cssVar('--color-text-primary', 'var(--color-text-primary)')
    const serif = cssToken('--font-serif', 'serif')
    const sans = cssToken('--font-sans', 'sans-serif')
    return {
      animation: false,
      tooltip: {
        trigger: 'axis',
        backgroundColor: surface,
        borderColor: input,
        borderWidth: 1,
        padding: [cssVarNumber('--spacing-xs', 4), cssVarNumber('--spacing-sm', 8)],
        textStyle: {
          color: text,
          fontFamily: sans,
          fontSize: cssVarNumber('--font-size-sm', 14),
        },
        extraCssText: cssDeclarations({
          'border-radius': 'var(--radius-md)',
          'box-shadow': 'var(--shadow-whisper)',
        }),
        formatter: (params: unknown) => formatTrendTooltip(params, data),
      },
      legend: {
        bottom: cssVarNumber('--spacing-xs', 4),
        textStyle: {
          color: secondary,
          fontFamily: serif,
          fontSize: cssVarNumber('--font-size-xs', 13),
          fontWeight: 500,
        },
      },
      grid: {
        ...TREND_GRID,
      },
      xAxis: {
        type: 'category',
        boundaryGap: false,
        data: data.map((item) => formatDate(item.createdAt, 'MM/DD')),
        axisLine: { lineStyle: { color: ring } },
        axisLabel: {
          color: tertiary,
          fontFamily: sans,
          fontSize: cssVarNumber('--font-size-xs', 13),
        },
      },
      yAxis: {
        type: 'value',
        min: 0,
        max: 10,
        axisLine: { lineStyle: { color: ring } },
        axisLabel: {
          color: tertiary,
          fontFamily: sans,
          fontSize: cssVarNumber('--font-size-xs', 13),
        },
        splitLine: { lineStyle: { color: border } },
      },
      series: [
        {
          name: '技术能力',
          type: 'line',
          smooth: true,
          data: data.map((item) => item.technical),
          lineStyle: { color: technical, width: 2 },
          itemStyle: { color: technical },
        },
        {
          name: '表达清晰度',
          type: 'line',
          smooth: true,
          data: data.map((item) => item.expression),
          lineStyle: { color: expression, width: 2 },
          itemStyle: { color: expression },
        },
        {
          name: '逻辑思维',
          type: 'line',
          smooth: true,
          data: data.map((item) => item.logic),
          lineStyle: { color: logic, width: 2 },
          itemStyle: { color: logic },
        },
      ],
    }
  }, data)
  return (
    <div
      className="h-(--layout-chart-block-size) min-h-(--layout-chart-block-size)"
      ref={ref}
      role="img"
      aria-label={`最近 ${data.length} 场面试的分数趋势`}
    />
  )
}

function formatTrendTooltip(params: unknown, data: AnalyticsTrendPoint[]) {
  const entries: unknown[] = Array.isArray(params) ? (params as unknown[]) : [params]
  const first = entries[0]
  if (!first || typeof first !== 'object' || !('dataIndex' in first)) return ''
  const dataIndex = Number((first as { dataIndex?: unknown }).dataIndex)
  const point = data[dataIndex]
  if (!point) return ''
  const lines = [`<div>${formatDate(point.createdAt, 'YYYY/MM/DD')}</div>`]
  for (const entry of entries) {
    if (!entry || typeof entry !== 'object') continue
    const item = entry as { marker?: string; seriesName?: string; value?: unknown }
    let value = ''
    if (typeof item.value === 'string') value = item.value
    else if (typeof item.value === 'number' || typeof item.value === 'boolean') {
      value = item.value.toString()
    } else if (item.value && typeof item.value === 'object') {
      value = JSON.stringify(item.value)
    }
    lines.push(`<div>${item.marker ?? ''} ${item.seriesName ?? ''}: ${value}</div>`)
  }
  return lines.join('')
}

function formatDate(dateString: string, format: 'MM/DD' | 'YYYY/MM/DD') {
  const date = new Date(dateString)
  const yyyy = date.getFullYear()
  const mm = String(date.getMonth() + 1).padStart(2, '0')
  const dd = String(date.getDate()).padStart(2, '0')
  return format === 'MM/DD' ? `${mm}/${dd}` : `${yyyy}/${mm}/${dd}`
}

function normalizeChartColor(value: string) {
  const srgbMatch = value.match(/^color\(srgb\s+([0-9.]+)\s+([0-9.]+)\s+([0-9.]+)/)
  if (!srgbMatch) return value
  const [, r, g, b] = srgbMatch
  return `rgb${'('}${Math.round(Number(r) * 255)}, ${Math.round(Number(g) * 255)}, ${Math.round(Number(b) * 255)})`
}

function resolveChartColor(value: string) {
  const probe = document.createElement('span')
  probe.style.color = value
  document.body.appendChild(probe)
  const computed = getComputedStyle(probe).color
  probe.remove()
  return normalizeChartColor(computed || value)
}

function cssVar(name: string, fallback: string) {
  const value = getComputedStyle(document.documentElement).getPropertyValue(name).trim()
  return resolveChartColor(value || fallback)
}

function cssToken(name: string, fallback: string) {
  return getComputedStyle(document.documentElement).getPropertyValue(name).trim() || fallback
}

function cssVarNumber(name: string, fallback: number) {
  const value = getComputedStyle(document.documentElement).getPropertyValue(name).trim()
  const parsed = Number.parseFloat(value)
  return Number.isFinite(parsed) ? parsed : fallback
}

function cssDeclarations(declarations: Record<string, string>) {
  return Object.entries(declarations)
    .map(([property, value]) => `${property}: ${value}`)
    .join('; ')
}
